### ISSUE TITLE
Roadmap to v2

### ISSUE THREAD

**Issue by xen0n** [xen0n/go-workwx#162]
* [ ] 切出 `v2` 分支
* [ ] 提升最低 Go 版本要求，提升一些期待已久的依赖库版本
* [ ] 开始引入 API-breaking changes #133
* [ ] Tag RC
* [ ] 等下游正面反馈
* [ ] Release

在 tag 出 `v2.0.0` 之前不预期出现任何问题。如果有，及时过来冒泡

**Comment by xen0n** [comment]
Time flies like an arrow!

Instead of indefinitely blocking progress and driving people away from the project, let's just start moving and merge things gradually.

Roadmap pulled out of #133:

* [ ] Cleanups
    - [ ] General Go Generics cleanups
    - [ ] Fix Chinglish
    - [ ] Fix things like `Id`
* [ ] `WorkwxFoo` -> `WeComFoo` (with compatibility aliases)
* [x] Access token provider (#72)
* [ ] Low-level API design (#55)
* [ ] Provide an easy-to-use global instance in a separate package & corresponding docs (discovered by looking at many usages in the wild)
